name: build

on:
  push:
    branches:
      - master

jobs:

  push-image:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: build image 
        run: |
          docker build -f front/Dockerfile --rm=false -t imneko/bustimer:latest .
      - name: push image
        run: |
          docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}}
          docker push imneko/bustimer:latest


  deploy:
    name: deploy to now
    needs: push-image
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v1
      - name: deploy
        uses: amondnet/vercel-action@v20
          with:
            vercel-token: ${{ secrets.ZEIT_TOKEN }} 
            vercel-args: '--prod' 
            vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
            vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
            working-directory: ./front
